# Lecture 7 - 10: The Roadmap for Text Analysis and Machine Learning

Text Analysis: The use of machine to augment our capacity to read text, including summary of the text, the search for specific contents of interest and text related to the current one.

This is a huge topic and we are employing various methods to this topic. Therefore, I summarized all 4 lectures into this single roadmap. So that you can get a bigger picture, and it is easier to locate where you are along the way. You may fold or unfold sections to get quicker access to topics that you need. It is also suggested that you refer to the lecture slides for more conceptual explanations of the content.

## The case for Lecture 7 to 10: Understanding Chinese Diplomacy with Text Analysis

Chinese Ministry of Foreign Affairs Press Conferences Corpus. It includes transcriptions of the Chinese MoFA's press conference, translated into English up until 2023. We will use this dataset many times in the following lectures. You can proceed to download it from the website yourself. After you have the data in your course folder, please organize it following the practices that we recommended.

- Data: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/BAKGET

- Paper: https://link.springer.com/article/10.1007/s11366-021-09762-3


You are recommended to read the data codebook (i.e., the documentation where the author of the paper records what each variable name means) before the lecture.

Reminder:

There are two versions of the data, one named `CMFA_PressCon_v4.xlsx`, which is the original data from the author of this paper. The other one is named `MoFA_bilingual.csv`, which is a bilingual version that includes both original Chinese texts and the English translation. Both versions can be found at the CMFA folder under the `Data` folder of this lecture. We will use them for the rest of this semester. Remember to import the correct one when we work on English or Chines text analysis.

## The Roadmap for Text Analysis and Machine Learning

**Lecture 7 Text Analysis I: Feature Extraction/Engineering**

1. Extract linguistic features from text data

* Tokenization

* Lemmatization

* POS tagging

* Stopwords removal

2. Extract entity features from text data.

* Names and lemmatized names

* Types

* Positions in token and among characters

1. Functionizing and batch processing a collection of documents

**Lecture 8 Text Analysis II: Word Frequency and Word Cloud**

1. Drawing word clouds using word frequencies

2. Plotting word frequencies

3. BoW model and tranformation

**Lecture 9: Topic Modelling and Traditional Models of Machine Learning**

1. Topic modelling in English and Chinese

  Classification models:
   
   - Data Input: Define X and y; Handling missing values; Training and testing sets
   - Data Processing: Define and Train model
   - Data output: Evaluate and interpret models

2. Logistic Regression

3. Decision Tree

4. Random Forest

5. Model Evaluations


**Lecture 10: Text Analysis with Classification Models and LLMs**

1. Text Classification
   - Speciality of Text Classification
   - Logistic Regression
   - Random Forest

2. LLM

Steps of setting up LLM in Colab
   - HuggingFace
   - Install packages
   - Importing LLM from HuggingFace   
   - Ask LLM questions
  
Application: Sentiment analysis and Named entity extration using LLM

**Quick words on good practices**

1. Troubleshooting Tip with Colab Notebook:
   - Splitting code into different code chunks help you identify the problem by locating which part of your code is problematic.
   - Make fragmented code chunks when you test your code before merging them for the final one.

2. Libraries need to be loaded only ONCE at the start of the notebook

## Lecture 7 Text Analysis I: Feature Extraction/Engineering

**Objective of Text Analysis**

We use machine to augment our capacity to READ text, including:

- Summarize the text

- Look for specific contents of interest

- Search for text related to the current one

**Unit of analysis**

Anslysis of texts can be done at different levels, including at the corpus level (i.e., the entire collection of documents), in which case we are interested in:

* What contents/ concepts are in this corpus? How frequent does each one appear?

* How frequently does the corpus discuss certain topic/ concept of your choice?

Or at the document level:

* What contents/ concepts are in this document? How frequent does each one appear?

* How frequently does the document discuss certain topic/ concept of your choice?

* Which documents is most similar to the document of interest?

Or only part of document (e.g., paragraph, sentence, word, phrase)

* Which paragraphs/ sentences/ words/ phrases are similar to the one of interest?

**Modern Approach**

Modern approach of text anslysis is the kind of methods before the recent boom of Large Language Models (i.e., LLM, e.g., ChatGPT, or the post-modern approach)
Despite the recent developments, modern approach is essential for forming basic understanding of text analysis and will be useful for years even with the new methods.

Some features for the modern approach:

* Computationally efficient: You do not need 100 highly powerful and expensive GPUs to train your model, like OpenAI and Deepseek does. You can perform modern text analysis even using your laptop.

* Good for data safety: Everything that Python processes remains in the memory and the machine that you use to process the text data. Nothing will be transferred to any third party. Unlike commercial large langauge models that might use your input as their training data. Also, the models that we employ are open-source. This means everyone can see their original codes and review the data security of these models.

* Inexpensive: Basically free, if you run it with Google Colab, which provides free computational resrouces.

**Mapping Text Anslysis to the Data Science workflow**

Even the type of data we deal with now changes to texts, the workflow doesn't change that much.

* Data Input:
  
  Load text data

* Data processing
  
  Extract linguistic features from text

  Extract substantive features from text, such as geopolotical entities.

* Data Output
  
  Save processed text data
  
  Visualize results of text analysis

**Warm-up exercise**

Please refer to the `Warm_up_Exercise_Week9Lecture7.ipynb` file for questions and suggested answers. After that, come back for the real dive into text analysis.

**Load Text Data**

Text data can come in various formats. The simplest one is "text in tables", including Excel, CSV, TXT, JSON, XML, HTML, or databases such as SQL, etc.

We work with the simplest format in class. You may come across other formats elsewhere. Don’t be intimidated. Remember there is nothing mysterious about these other formats. They were invented for efficient data storage and retrieval. Python has functions to work with essentially all popular formats. Just look it up.

In [ ]:
import pandas as pd

**Case: Understanding Chinese Diplomacy with Text Analysis**

Chinese Ministry of Foreign Affairs Press Conferences Corpus. If you haven't downloaded the data yet, now is the time to do it.

- Data: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/BAKGET

- Paper: https://link.springer.com/article/10.1007/s11366-021-09762-3

In [ ]:
# Again, this is only the path that works for me. Replace this with your own data path.
data_url = "/content/drive/MyDrive/POLI3148/Lecture7/data_raw/CMFA_PressCon_v4.xlsx"

Load the text data using Pandas.

In [ ]:
df = pd.read_excel(data_url)

Inspect this dataframe as a starting point. Examining one or multiple record(s) of your dataset is always a good way to start any data analysis.

In [ ]:
df.loc[0,:].to_dict()

{'id_orig': 1,
 'id_split': 1,
 'id': 1,
 'link': 'http://web.archive.org/web/20030907084940/http://www.fmprc.gov.cn:80/eng/xwfw/2510/2511/t14653.htm',
 'spokesperson': 'Zhang Qiyue',
 'day': 15,
 'month': 'October',
 'year': 2002,
 'date': datetime.datetime(2002, 10, 15, 0, 0),
 'question': 'How many Hong Kong and Taiwan people were injured in the blasts in the Bali Island, Indonesia? Are there any Mainland citizens injured? What has the Chinese Embassy in Indonesia done in this regard?',
 'answer': 'China is always opposed to terrorism of all forms. We strongly condemn this violent activity and would like to express deep sympathy for victims of Indonesia and other countries and their relatives. Chinese leaders have already sent a telegraph of comfort to Indonesian leaders and expressed that China would support the Indonesian Government in its efforts to fight against terrorism. The Chinese Embassy in Indonesia has been closely following this incident and has already sent consular officers to the Bali Island to learn the casualty facts of Chinese citizens, residents of Hong Kong and Macao as well as Taiwan compatriots. According to the hospitalization list provided by the Indonesian police, one Mainland citizen was injured and consular officers of the Chinese Embassy have already went to see him. The Chinese Embassy in Indonesia will continue to follow this incident and is now trying to learn the conditions of Chinese citizens there through various channels and offer any necessary assistance.',
 'question_lem': 'how many Hong Kong and Taiwan people be injure in the blast in the Bali Island, Indonesia? be there any Mainland citizen injure? what have the chinese Embassy in Indonesia do in this regard?',
 'answer_lem': 'China be always opposed to terrorism of all form. we strongly condemn this violent activity and would like to express deep sympathy for victim of Indonesia and other country and they relative. chinese leader have already send a telegraph of comfort to indonesian leader and express that China would support the indonesian Government in its effort to fight against terrorism. the chinese Embassy in Indonesia have be closely follow this incident and have already send consular officer to the Bali Island to learn the casualty fact of chinese citizen, resident of Hong Kong and Macao as well as Taiwan compatriot. accord to the hospitalization list provide by the indonesian police, one Mainland citizen be injure and consular officer of the Chinese Embassy have already go to see he. the chinese Embassy in Indonesia will continue to follow this incident and be now try to learn the condition of chinese citizen there through various channel and offer any necessary assistance.',
 'who_asked': '-',
 'q_loc': 'Taiwan; Mainland; Indonesia; Hong Kong; Bali Island',
 'q_per': '-',
 'q_org': '-',
 'q_misc': 'Chinese',
 'a_loc': 'Taiwan; Mainland; Macao; Indonesia; Hong Kong; China; Bali Island',
 'a_per': '-',
 'a_org': 'Government',
 'a_misc': 'Indonesian; Chinese',
 'a_sentiment': 2.35494453708331,
 'q_sentiment': 0.939969112475713}

### 1. Extract Linguistic Features from Text

Extracting linguistic feature (“linguistic annotation”) is an essential pre-step in the modern text analysis approach. Techniques that we are primarily interested in include:
* Tokenization: Segmenting text into words, punctuations marks etc. Usually for English, the boundaries are drawn by a space between two tokens. SpaCy does this automatically for us.

* Stemming/Lemmatization: Assigning the base forms of words. For example, the lemma of “was” is “be”, and the lemma of “rats” is “rat”. In other words, it changes words that are inflected for gramatical reasons back to their "basic" forms.

* Part-of-speech tagging: Assigning word types to these tokens, such as "work" is a verb and "China" is a noun.

* Stopword removal: Remove words that occur commonly across documents. They are typically not substantively meaningful. Examples: “the” “a” “to”, "of".

To perform this, we use SpaCy, a tool for extracting linguistic and substantive features with only a few lines of code.

https://spacy.io/
It is very friendly for beginners, free, easy to use, nultifunctional and multilingual.

In [ ]:
import spacy
nlp = spacy.load("en_core_web_sm")

You need to load the correct model for your target language. English model will perform very badly if the text data are all in Irish.

For “en_core_web_sm”:

en: English, which means there are also other languages available.

core: a general-purpose language model

web: the “pipeline” is trained on web data (as opposed to news data)

sm: “small” size (as opposed to middle, large, etc)

**Getting Linguistic features using List Comprehension**

These are the commands that we use to get these features. Remember from the beginning of the semester where we introduced "list comprehension"? Let's go over it once again.

Originally, if we want to create a list, we would:

In [ ]:
# I want to creata a new list that consists of fruit names that contains English letter "a".
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
newlist = []

for x in fruits:
  if "a" in x:
    newlist.append(x)

print(newlist)

But that seems to be very long and excessive for many programmers. With list comprehension, we can significantly shorten that into:

In [ ]:
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]

newlist = [x for x in fruits if "a" in x]

print(newlist)

With this, you are practically running a for loop within that newly created list. In the same way, we get get the linguistic features relatively quickly with list comprehension:

Get raw tokens:

	`[word for word in doc]`

I.e., Include the word, if the word exists in the document.

	`[word.text for word in doc]`

Get low-cased tokens

	`[word.lower_ for word in doc]`
  
I.e., include the lowercase of the word, if the word exists in the document.

Get lemmatized tokens

	`[word.lemma_ for word in doc]`

I.e., include the lemmatized word, if the word exists in the document.

Get part-of-speech tags of tokens

	`[word.pos_ for word in doc]`

Get stopword indicators for tokens

	`[word.is_stop for word in doc]`

To make a dataframe that contains everything

```
pd.DataFrame(
  {
      'token': [word for word in doc],
      'lower': [word.lower_ for word in doc],
      'lemma': [word.lemma_ for word in doc],
      'pos': [word.pos_ for word in doc],
      'stopword': [word.is_stop for word in doc]
  }
)
```
The interpretation of the above is that: We are creating a dictionary of lists, where the list names are the key and the lists themselves are the values. And then we use this dictionary to create a dataframe, which takes the keys as the column names, and make the lists the columns themselves. Let's apply this to one document, which is the first question in this dataset.

In [ ]:
# Tokenize the first question using nlp().
doc = nlp(df.loc[0, "question"])

In [ ]:
# Get all linguistic features and print out the dataframe.
ling_features = pd.DataFrame(
  {
      'token': [word for word in doc],
      'lower': [word.lower_ for word in doc],
      'lemma': [word.lemma_ for word in doc],
      'pos': [word.pos_ for word in doc],
      'stopword': [word.is_stop for word in doc]
  }
)
ling_features

        token      lower      lemma    pos  stopword
0         How        how        how  SCONJ      True
1        many       many       many    ADJ      True
2        Hong       hong       Hong  PROPN     False
3        Kong       kong       Kong  PROPN     False
4         and        and        and  CCONJ      True
5      Taiwan     taiwan     Taiwan  PROPN     False
6      people     people     people   NOUN     False
7        were       were         be    AUX      True
8     injured    injured     injure   VERB     False
9          in         in         in    ADP      True
10        the        the        the    DET      True
11     blasts     blasts      blast   NOUN     False
12         in         in         in    ADP      True
13        the        the        the    DET      True
14       Bali       bali       Bali  PROPN     False
15     Island     island     Island  PROPN     False
16          ,          ,          ,  PUNCT     False
17  Indonesia  indonesia  Indonesia  PROPN     False
18          ?          ?          ?  PUNCT     False
19        Are        are         be    AUX      True
20      there      there      there   PRON      True
21        any        any        any    DET      True
22   Mainland   mainland   Mainland  PROPN     False
23   citizens   citizens    citizen   NOUN     False
24    injured    injured     injure   VERB     False
25          ?          ?          ?  PUNCT     False
26       What       what       what   PRON      True
27        has        has       have    AUX      True
28        the        the        the    DET      True
29    Chinese    chinese    Chinese  PROPN     False
30    Embassy    embassy    Embassy  PROPN     False
31         in         in         in    ADP      True
32  Indonesia  indonesia  Indonesia  PROPN     False
33       done       done         do   VERB      True
34         in         in         in    ADP      True
35       this       this       this    DET      True
36     regard     regard     regard   NOUN     False
37          ?          ?          ?  PUNCT     False

That's it! Let's move to the entity features below.

### 2. Extract Substantive Features (Named Entities) from Text

Substantive features, such as named entities, are also helpful. For example, we can know which entities do the press conferences mention the most.

Note: In this operation, data are returned with a different logic. Linguistic features are returned at token-level, which means the features are available for each words. But substantive features are return in document-level, which means we get a table of these features for each document.

Named Entities are in doc.ents, therefore, to extract...

Named Entities

```
[ne.text for ne in doc.ents]
```

Lemmatized Named Entities

```
[ne.lemma_ for ne in doc.ents]
```

Types of Named Entities

```
[ne.label_ for ne in doc.ents]
```

Starting and ending positions (among tokens)

```
[ne.start for ne in doc.ents]

[ne.end for ne in doc.ents]
```

Starting and ending positions (among characters)

```
[ne.start_char for ne in doc.ents]

[ne.end_char for ne in doc.ents]
```

To make a dataframe that contains everything:


```
pd.DataFrame(
    {
        'ne': [ne.text for ne in doc.ents],
        'ne_lemma': [ne.lemma_ for ne in doc.ents],
        'ne_label': [ne.label_ for ne in doc.ents],
        'ne_start': [ne.start for ne in doc.ents],
        'ne_end': [ne.end for ne in doc.ents],
        'ne_start_char': [ne.start_char for ne in doc.ents],
        'ne_end_char': [ne.end_char for ne in doc.ents]
    }
)
```

With the previous examples for linguistic features, this should become intuitive now.

In [ ]:
ne_features = pd.DataFrame(
    {
        'ne': [ne.text for ne in doc.ents],
        'ne_lemma': [ne.lemma_ for ne in doc.ents],
        'ne_label': [ne.label_ for ne in doc.ents],
        'ne_start': [ne.start for ne in doc.ents],
        'ne_end': [ne.end for ne in doc.ents],
        'ne_start_char': [ne.start_char for ne in doc.ents],
        'ne_end_char': [ne.end_char for ne in doc.ents]
    }
)
ne_features

,ne,ne_lemma,ne_label,ne_start,ne_end,ne_start_char,ne_end_char
0,Hong Kong,Hong Kong,GPE,2,4,9,18
1,Taiwan,Taiwan,GPE,5,6,23,29
2,the Bali Island,the Bali Island,LOC,13,16,67,82
3,Indonesia,Indonesia,GPE,17,18,84,93
4,Mainland,Mainland,NORP,22,23,109,117
5,the Chinese Embassy,the Chinese Embassy,ORG,28,31,145,164
6,Indonesia,Indonesia,GPE,32,33,168,177

### 3. Functionizing and batch processing

**Creating a Function of Extracting Linguistic and Entity Features**

What if you want to make both processes more automatic? In that way, you can just specify the texts you need to analyze, then the rest of the job is for Python. It is actually not difficult. All you need is to automate the tokenization process.

In [ ]:
def text_analysis(text_input):
  doc = nlp(text_input)
  extract_ling = pd.DataFrame(
    {
        "token": [word.text for word in doc],
        "lower": [word.lower_ for word in doc],
        "lemma": [word.lemma_ for word in doc],
        "pos": [word.pos_ for word in doc],
        "stopword": [word.is_stop for word in doc],
    })

  extract_ne = pd.DataFrame(
    {
        'ne': [ne.text for ne in doc.ents],
        'ne_lemma': [ne.lemma_ for ne in doc.ents],
        'ne_label': [ne.label_ for ne in doc.ents],
        'ne_start': [ne.start for ne in doc.ents],
        'ne_end': [ne.end for ne in doc.ents],
        'ne_start_char': [ne.start_char for ne in doc.ents],
        'ne_end_char': [ne.end_char for ne in doc.ents],
    })
  return extract_ling, extract_ne

IMPORTANT: What have we achieved? We have just turned unstructured data into structured data.

**Think about being economic and the memory management**

We created a function that first analyzes all features that we might need, then stores the features in dictionaries and corresponding dataframes. This is suitable for processing documents that are not exceedingly long, such as MoFA press conference for a single day ot week.If you would like to do this with 1000 documents, it is very likely that you will run out of memory. And the processing speed will ve very slow. See the next section for batch processing.

**Extracting Features from a Collection of Documents**

We have just performed all these analyses to one document. What shall we do are to scale it up for a collection of documents? For example: Extract features from all the questions asked in the MoFA conferences in 2023?


Using the function we created, we can:

1. Create a subset of the dataframe covering Q&A in 2023

2. Locate the “Question” column

3. Repeatedly perform the same text analysis to every question

In [ ]:
# Filter out the rows of 2023
df_2023 = df.loc[df.year == 2023, :].reset_index()

# Create two lists that we store the output dataframes
result_ling_ls = []
result_ne_ls = []

# Write a for loop to loop through all texts
for id, text in zip(df_2023.id, df_2023.question): # Remember our old friend zip()?
  r_ling, r_ne = text_analysis(text)

  # Store the id that will be used later for merging
  r_ling['id'] = id
  r_ne['id'] = id

  # Append each resulting dataframe to the list
  result_ling_ls.append(r_ling)
  result_ne_ls.append(r_ne)

  # Uncomment if you need to check the process
  #print(id)

# Finally, concatonate the two lists of dataframes into two huge dataframes
text_ling = pd.concat(result_ling_ls, ignore_index = True)
text_ne = pd.concat(result_ne_ls, ignore_index = True)

With this, you can ask more questions with the merged dataset:

For example, how did the contents of questions vary across time? And across news media?

**Save processed text**

We save the the structured text data, so that we will not have to re-do the feature extraction everytime. It saves our time when doing following analyses. Still, remember to follow the best practices for folder organization.

In [ ]:
# Remember to change the path to your data_processed folder when saving them.
result_ling_df.to_csv("text_question_ling.csv", index = False)
result_ne_df.to_csv("text_question_ne.csv", index = False)

Want to know more?

Try it yourself: Apply it to a different language.

`spacy.cli.download("zh_core_web_sm")
`

`
nlp = spacy.load("zh_core_web_sm")
`

Caveat: Linguistic features that we can generate for English need not be available for other language. For example, there is no lemmatization for Chinese. You may need to read the documentation. But the documentation is not always informative. Poke around. Try.